name: spooktacular_storybook
description: A spooky interactive Flutter storybook
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  audioplayers: ^2.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/ghost.png
    - assets/images/pumpkin.png
    - assets/images/bat.png
    - assets/images/candy.png
    - assets/images/jumpscare.png
    - assets/audio/background.mp3
    - assets/audio/jumpscare.mp3
    - assets/audio/success.mp3
